First draft of sequence diagrams
mikebowyer/ECE528_Project pull request #2
Opened 2021-03-23 00:50 UTC by mikebowyer

2021-03-23 01:31 UTC, tsteiner4 commented on sequence_diagrams/imaged_pushed_to_API_Sequence.wsd
> +AWS_Rekognition --> AWS_Rekognition: Detect Conecnts ofImage
Detect Contents of Image? Typo I think

2021-03-25 01:28 UTC, ktopolov commented
I've never used the review feature; not sure if I have to hit a button to say I looked it over

2021-03-25 01:32 UTC, tsteiner4 requested changes
See comment, possible typo on line 15 in imaged_pushed_to_API_Sequence

2021-03-25 01:33 UTC, tsteiner4 commented
> I've never used the review feature; not sure if I have to hit a button to say I looked it over

On the files changed tab, you can click Review Changes and then select "Approve"

2021-03-25 01:40 UTC, ktopolov commented
Worth checking the diagram; it says that the image will be stored in S3 with the bounding box, while the labels and initial metadata are stored in Dynamo.

Shouldn't the bounding box be stored with the rest of the metadata in Dynamo? Not sure how we would store the image with the bounding box, unless we impose the box on top and re-save it. But then we lose the original image

2021-03-25 01:40 UTC, ktopolov approved these changes

2021-03-26 02:22 UTC, mikebowyer commented on sequence_diagrams/imaged_pushed_to_API_Sequence.wsd
> +AWS_Rekognition --> AWS_Rekognition: Detect Conecnts ofImage
Yep type, it was resolved in my latest commit.

2021-03-26 02:23 UTC, mikebowyer commented
@ktopolov , I think you raise a good point. My perception was that we can just store the single image with any bounding boxes on it, that way we don't have to store the image twice (with and without bounding box). But We could certainly store bounding box information in the DynamoDB as well and then render a bounding box whenever we desired. I am open to both solutions. 
@tsteiner4 do you have preference here?

2021-03-26 03:02 UTC, tsteiner4 commented
> @ktopolov , I think you raise a good point. My perception was that we can just store the single image with any bounding boxes on it, that way we don't have to store the image twice (with and without bounding box). But We could certainly store bounding box information in the DynamoDB as well and then render a bounding box whenever we desired. I am open to both solutions.
> @tsteiner4 do you have preference here?

It is a lot easier to source an image from a URL than trying to add a box onto it as well. [Link](https://blog.mturk.com/tutorial-generating-images-with-bounding-boxes-on-the-fly-using-aws-lambda-690d2301a5ff) shows how to make a lambda function to do this, so that is probably how I would do it. I can do this in the html for the file if that is preferred to save storage.

2021-03-27 14:57 UTC, merged